// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO5krFgfTH1oePXXx5uuAVqarUiS7_tMg',
    appId: '1:413404950438:web:3247263906010cfa37e967',
    messagingSenderId: '413404950438',
    projectId: 'skolappen',
    authDomain: 'skolappen.firebaseapp.com',
    storageBucket: 'skolappen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpBzLPh2n-8TBjvSdl-N-Ep_fuhIzNSA',
    appId: '1:413404950438:android:04c38b3f80a255f637e967',
    messagingSenderId: '413404950438',
    projectId: 'skolappen',
    storageBucket: 'skolappen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Cul-du8elmscLGJt_0R4R109mfK9ETA',
    appId: '1:413404950438:ios:1f6ac314b1203c0a37e967',
    messagingSenderId: '413404950438',
    projectId: 'skolappen',
    storageBucket: 'skolappen.appspot.com',
    iosClientId: '413404950438-apnsfdmocrhjj4a431d76mmnnu6c8jrg.apps.googleusercontent.com',
    iosBundleId: 'se.solidred.skolappen',
  );
}
